"""Generate the flash-resident, upright 1bpp mascot (requires Pillow)."""

from pathlib import Path

from PIL import Image, ImageEnhance, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parents[1]
WIDTH, HEIGHT = 224, 336


def main():
    with Image.open(ROOT / "src/images/Mascot.png") as source:
        background = Image.new("RGBA", source.size, "white")
        background.alpha_composite(source.convert("RGBA"))
        image = ImageOps.contain(background.convert("RGB"), (WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (WIDTH, HEIGHT), "white")
    canvas.paste(image, ((WIDTH - image.width) // 2, (HEIGHT - image.height) // 2))
    gray = ImageEnhance.Contrast(ImageOps.grayscale(canvas)).enhance(1.15)
    gray = gray.filter(ImageFilter.UnsharpMask(radius=0.7, percent=140, threshold=3))
    bitmap = gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
    data = bitmap.tobytes()
    assert len(data) == WIDTH * HEIGHT // 8
    rows = ["    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 19]) + ","
            for i in range(0, len(data), 19)]
    header = (
        "#pragma once\n#include <cstdint>\n\n"
        "// Generated by scripts/generate_mascot.py. Row-major, MSB-first; 0 = ink.\n"
        f"static constexpr int MASCOT_WIDTH = {WIDTH};\n"
        f"static constexpr int MASCOT_HEIGHT = {HEIGHT};\n"
        "static constexpr uint8_t MASCOT_BITMAP[] = {\n"
        + "\n".join(rows) + "\n};\n"
        "static_assert(sizeof(MASCOT_BITMAP) == MASCOT_WIDTH * MASCOT_HEIGHT / 8);\n"
    )
    (ROOT / "src/images/Mascot.h").write_text(header)
    print(f"Generated {WIDTH}x{HEIGHT} mascot: {len(data)} flash bytes")


if __name__ == "__main__":
    main()
