#!/usr/bin/env python3
"""Generate the offline, flash-resident Thai dictionary (no runtime dependencies)."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import struct
import zlib

MAX_WORD_CODEPOINTS = 70
BLOCK_WORDS = 16


def load_words(path: Path, *, local: bool) -> tuple[set[str], dict[str, int], bytes]:
    raw = path.read_bytes()
    try:
        text = raw.decode("utf-8", errors="strict")
    except UnicodeDecodeError as error:
        line = raw[:error.start].count(b"\n") + 1
        raise ValueError(f"{path}:{line}: malformed UTF-8") from error
    words: set[str] = set()
    counts = {"lines": 0, "rejected_empty": 0, "rejected_non_thai": 0, "duplicates": 0}
    for line, word in enumerate(text.splitlines(), 1):
        counts["lines"] += 1
        # Empty files are allowed. An explicit blank local line is an invalid entry.
        if not word or not all(0x0E01 <= ord(cp) <= 0x0E5B for cp in word):
            reason = "empty" if not word else "non_thai"
            if local:
                raise ValueError(f"{path}:{line}: invalid local entry ({reason})")
            counts[f"rejected_{reason}"] += 1
            continue
        if len(word) > MAX_WORD_CODEPOINTS:
            raise ValueError(f"{path}:{line}: {len(word)} codepoints exceeds {MAX_WORD_CODEPOINTS}; "
                             "revise the bounded analyzer window explicitly")
        if word in words:
            counts["duplicates"] += 1
        words.add(word)
    return words, counts, raw


def encode(words: list[str]) -> tuple[bytes, list[int]]:
    data = bytearray()
    offsets: list[int] = []
    previous = b""
    for index, word in enumerate(words):
        symbols = bytes(ord(cp) - 0x0E00 for cp in word)
        prefix = 0
        if index % BLOCK_WORDS == 0:
            offsets.append(len(data))
        else:
            while prefix < min(len(previous), len(symbols)) and previous[prefix] == symbols[prefix]:
                prefix += 1
        suffix = symbols[prefix:]
        data.extend((prefix, len(suffix)))
        data.extend(suffix)
        previous = symbols
    offsets.append(len(data))
    return bytes(data), offsets


def generate(input_path: Path, extra_path: Path, output_path: Path, report_path: Path) -> dict:
    source, source_counts, source_raw = load_words(input_path, local=False)
    extra, extra_counts, extra_raw = load_words(extra_path, local=True)
    words = sorted(source | extra)
    data, offsets = encode(words)
    offset_bytes = b"".join(struct.pack("<I", offset) for offset in offsets)
    crc = zlib.crc32(data + offset_bytes)
    maximum = max(map(len, words), default=0)
    # Standard C++ forbids zero-sized arrays; empty generated data has a one-byte sentinel.
    data_lines = ["    " + ", ".join(f"0x{x:02X}" for x in data[i:i + 16]) + ","
                  for i in range(0, len(data), 16)] or ["    0x00,"]
    offset_lines = ["    " + ", ".join(f"{x}u" for x in offsets[i:i + 12]) + ","
                    for i in range(0, len(offsets), 12)]
    header = ("// Generated by scripts/generate_thai_dictionary.py; do not edit.\n"
              "// Include only from ThaiDictionary.cpp. Source provenance: ../dictionary/NOTICE.\n"
              "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n"
              "namespace thai::generated {\n"
              "alignas(4) static constexpr uint8_t DATA[] = {\n" + "\n".join(data_lines) + "\n};\n"
              "alignas(4) static constexpr uint32_t OFFSETS[] = {\n" + "\n".join(offset_lines) + "\n};\n"
              f"static constexpr size_t DATA_BYTES = {len(data)};\n"
              f"static constexpr size_t OFFSET_COUNT = {len(offsets)};\n"
              f"static constexpr size_t WORD_COUNT = {len(words)};\n"
              f"static constexpr size_t MAX_WORD_CODEPOINTS = {maximum};\n"
              f"static constexpr size_t BLOCK_WORDS = {BLOCK_WORDS};\n"
              f"static constexpr uint32_t DATA_ID = 0x{crc:08X}u;\n"
              "}  // namespace thai::generated\n").encode("ascii")
    report = {
        "format_version": 1, "block_words": BLOCK_WORDS,
        "source_sha256": hashlib.sha256(source_raw).hexdigest(),
        "extra_sha256": hashlib.sha256(extra_raw).hexdigest(),
        "source": source_counts, "extra": extra_counts,
        "rejected_source_entries": source_counts["rejected_empty"] + source_counts["rejected_non_thai"],
        "word_count": len(words), "maximum_word_codepoints": maximum,
        "data_bytes": len(data), "offset_count": len(offsets), "offset_bytes": len(offset_bytes),
        "flash_bytes": max(1, len(data)) + len(offset_bytes),
        "decoder_scratch_bytes": MAX_WORD_CODEPOINTS + 1,
        "data_crc32": f"{crc:08x}", "output_sha256": hashlib.sha256(header).hexdigest(),
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(header)
    report_path.write_bytes((json.dumps(report, indent=2, sort_keys=True) + "\n").encode("utf-8"))
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("input", "extra", "output", "report"):
        parser.add_argument(f"--{name}", type=Path, required=True)
    args = parser.parse_args()
    try:
        report = generate(args.input, args.extra, args.output, args.report)
    except (ValueError, OSError) as error:
        parser.exit(2, f"error: {error}\n")
    print(f"{report['word_count']} words; {report['flash_bytes']} flash bytes; CRC32 {report['data_crc32']}")


if __name__ == "__main__":
    main()
