"""Generate flash-resident light/dark 1bpp mascots (requires Pillow)."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parents[1]
WIDTH, HEIGHT = 224, 336


def bitmap_declaration(name, bitmap):
    data = bitmap.tobytes()
    assert len(data) == WIDTH * HEIGHT // 8
    rows = ["    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 19]) + ","
            for i in range(0, len(data), 19)]
    return (
        f"static constexpr uint8_t {name}[] = {{\n"
        + "\n".join(rows) + "\n};\n"
        f"static_assert(sizeof({name}) == MASCOT_WIDTH * MASCOT_HEIGHT / 8);\n"
    )


def main():
    with Image.open(ROOT / "src/images/Mascot.png") as source:
        background = Image.new("RGBA", source.size, "white")
        background.alpha_composite(source.convert("RGBA"))
        image = ImageOps.contain(background.convert("RGB"), (WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", (WIDTH, HEIGHT), "white")
    canvas.paste(image, ((WIDTH - image.width) // 2, (HEIGHT - image.height) // 2))
    gray = ImageEnhance.Contrast(ImageOps.grayscale(canvas)).enhance(1.15)
    gray = gray.filter(ImageFilter.UnsharpMask(radius=0.7, percent=140, threshold=3))
    bitmap = gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)

    # Remove only border-connected white, preserving the face and clothing.
    exterior = ImageOps.grayscale(canvas).point(lambda value: 255 if value >= 245 else 0)
    ImageDraw.floodfill(exterior, (0, 0), 128)
    silhouette = exterior.point(lambda value: 0 if value == 128 else 255)
    outline = silhouette.filter(ImageFilter.MaxFilter(3))
    dark = Image.new("L", canvas.size, 0)
    dark.paste(255, mask=outline)
    dark.paste(bitmap.convert("L"), mask=silhouette)
    # The caller inverts the whole screen; bake its inverse into the framebuffer.
    dark_bitmap = ImageOps.invert(dark).convert("1", dither=Image.Dither.NONE)
    header = (
        "#pragma once\n#include <cstdint>\n\n"
        "// Generated by scripts/generate_mascot.py. Row-major, MSB-first; 0 = ink.\n"
        f"static constexpr int MASCOT_WIDTH = {WIDTH};\n"
        f"static constexpr int MASCOT_HEIGHT = {HEIGHT};\n"
        + bitmap_declaration("MASCOT_BITMAP", bitmap)
        + "\n// Counter-inverted mascot for a dark screen; silhouette/outline baked offline.\n"
        + bitmap_declaration("MASCOT_DARK_BITMAP", dark_bitmap)
    )
    (ROOT / "src/images/Mascot.h").write_text(header)
    print(f"Generated two {WIDTH}x{HEIGHT} mascots: {2 * WIDTH * HEIGHT // 8} flash bytes")


if __name__ == "__main__":
    main()
