include_guard(GLOBAL)

# A firmware cross compiler cannot produce the host construction utility.
# Firmware builds consume the artifacts generated by a separate host build.
if(CMAKE_CROSSCOMPILING)
    return()
endif()

find_package(Python3 REQUIRED COMPONENTS Interpreter)

set(NATIVE_TEXT_ASSET_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated" CACHE PATH
    "Build output directory for generated native text assets")
get_filename_component(NATIVE_TEXT_ASSET_OUTPUT_DIR "${NATIVE_TEXT_ASSET_OUTPUT_DIR}"
    ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
set(NATIVE_THAI_DICTIONARY_DATA_DIR "${CMAKE_CURRENT_LIST_DIR}/../vendor/libthai-0.1.30/data")
set(NATIVE_THAI_DICTIONARY_GENERATOR
    "${CMAKE_CURRENT_LIST_DIR}/../../EpdFont/scripts/build-native-thai-dictionary.py")
set(NATIVE_THAI_DICTIONARY_VENDOR_MANIFEST "${CMAKE_CURRENT_LIST_DIR}/../vendor-sources.json")

add_executable(NativeThaiDictionaryBuilder
    "${CMAKE_CURRENT_LIST_DIR}/../tools/NativeThaiDictionaryBuilder.cpp")
target_include_directories(NativeThaiDictionaryBuilder PRIVATE "${CMAKE_CURRENT_LIST_DIR}/..")
# Construction has a separate 64 MiB host budget. The runtime NativeAllocator
# retains its fixed 4 MiB cap; never link both allocator definitions here.
target_link_libraries(NativeThaiDictionaryBuilder PRIVATE NativeDatrie NativeDictionaryAllocator)
set_target_properties(NativeThaiDictionaryBuilder PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED YES
    CXX_EXTENSIONS NO
)
if(MINGW)
    target_link_options(NativeThaiDictionaryBuilder PRIVATE -municode)
endif()

# Ask the same parser used for generation for the explicit upstream dependency
# list. New tdict files not named by TDICT_SRC must not enter the dictionary.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${NATIVE_THAI_DICTIONARY_DATA_DIR}/Makefile.am"
    "${NATIVE_THAI_DICTIONARY_GENERATOR}")
execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${NATIVE_THAI_DICTIONARY_GENERATOR}"
        --data-dir "${NATIVE_THAI_DICTIONARY_DATA_DIR}" --list-inputs
    RESULT_VARIABLE native_thai_inputs_result
    OUTPUT_VARIABLE native_thai_inputs
    ERROR_VARIABLE native_thai_inputs_error
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT native_thai_inputs_result EQUAL 0)
    message(FATAL_ERROR "Cannot parse LibThai TDICT_SRC: ${native_thai_inputs_error}")
endif()
string(REPLACE "\r\n" "\n" native_thai_inputs "${native_thai_inputs}")
string(REPLACE "\n" ";" NATIVE_THAI_DICTIONARY_INPUTS "${native_thai_inputs}")

set(NATIVE_THAI_DICTIONARY_HEADER "${NATIVE_TEXT_ASSET_OUTPUT_DIR}/NativeThaiDictionary.generated.h")
set(NATIVE_THAI_DICTIONARY_SOURCE "${NATIVE_TEXT_ASSET_OUTPUT_DIR}/NativeThaiDictionary.generated.cpp")
set(NATIVE_THAI_DICTIONARY_FILE "${NATIVE_TEXT_ASSET_OUTPUT_DIR}/thbrk.tri")
set(NATIVE_THAI_DICTIONARY_METADATA "${NATIVE_TEXT_ASSET_OUTPUT_DIR}/thbrk.metadata.json")
set(NATIVE_THAI_DICTIONARY_WORDS "${NATIVE_TEXT_ASSET_OUTPUT_DIR}/tdict.txt")
set(NATIVE_THAI_DICTIONARY_INCLUDE_DIR "${NATIVE_TEXT_ASSET_OUTPUT_DIR}")

add_custom_command(
    OUTPUT
        "${NATIVE_THAI_DICTIONARY_HEADER}"
        "${NATIVE_THAI_DICTIONARY_SOURCE}"
        "${NATIVE_THAI_DICTIONARY_FILE}"
        "${NATIVE_THAI_DICTIONARY_METADATA}"
        "${NATIVE_THAI_DICTIONARY_WORDS}"
    COMMAND "${Python3_EXECUTABLE}" "${NATIVE_THAI_DICTIONARY_GENERATOR}"
        --data-dir "${NATIVE_THAI_DICTIONARY_DATA_DIR}"
        --vendor-manifest "${NATIVE_THAI_DICTIONARY_VENDOR_MANIFEST}"
        --builder "$<TARGET_FILE:NativeThaiDictionaryBuilder>"
        --output "${NATIVE_TEXT_ASSET_OUTPUT_DIR}"
    DEPENDS
        NativeThaiDictionaryBuilder
        "${NATIVE_THAI_DICTIONARY_GENERATOR}"
        "${NATIVE_THAI_DICTIONARY_VENDOR_MANIFEST}"
        "${NATIVE_THAI_DICTIONARY_DATA_DIR}/Makefile.am"
        "${NATIVE_THAI_DICTIONARY_DATA_DIR}/thbrk.abm"
        ${NATIVE_THAI_DICTIONARY_INPUTS}
    COMMENT "Building and embedding the complete pinned LibThai dictionary"
    VERBATIM
)
add_custom_target(NativeThaiDictionaryAssets DEPENDS
    "${NATIVE_THAI_DICTIONARY_HEADER}"
    "${NATIVE_THAI_DICTIONARY_SOURCE}"
    "${NATIVE_THAI_DICTIONARY_FILE}"
    "${NATIVE_THAI_DICTIONARY_METADATA}"
    "${NATIVE_THAI_DICTIONARY_WORDS}"
)
